language: r
r:
  - release
  - devel
cache: packages

# Be strict when checking our package
warnings_are_errors: true

before_install:
 - cd RPackage
 
after_success:
 - cd ..
 - bash tests/travis_tests.sh
 