language: r
r:
  - 3.3.2
  - release
  - devel
cache: packages

# Be strict when checking our package
warnings_are_errors: true

before_install:
 - cd RPackage
 
after_success:
 - cd ..
 - bash tests/travis_tests.sh
 - . STIMA_ERROR.sh
 - cat STIMA_ERROR.sh
 - echo $STIMA_ERROR
 - exit $STIMA_ERROR
 
